support transitive extension ini TM definitions
w3c/wot-thing-description pull request #1478
Opened 2022-04-27 11:12 UTC by sebastiankb

solves #1374

2022-04-27 12:01 UTC, thjaeckle requested changes
Remarks see my inline comments..

2022-04-27 12:01 UTC, thjaeckle commented on index.template.html
> +        Consequently, the <code>ColorableLamp</code> TM also extend all definitions of both <code>DimmableLamp</code> and <code>SwitchableLamp</code>. It should be ensured that no recursive extension
Shouldn't the formulation "It should be ensured that no recursive extensions are defined" be instead:
"Recursive extensions leading to an infinite loop MUST NOT be defined."?

2022-05-02 08:10 UTC, thjaeckle commented on index.html
> +        The <code>tm:extends</code> and the import mechanism based on <code>tm:ref</code> explicitly support transitive extension (a hierarchy of extensions).
"explicitly support" -> "explicitly support**s**"

2022-05-02 08:11 UTC, thjaeckle commented on index.html
> +        Consequently, the "A" TM also extend all definitions of both "B" and "C".
"also extend" -> "extend**s**"

2022-05-02 08:11 UTC, thjaeckle requested changes
addressed 2 little findings in inline comments

2022-05-04 15:48 UTC, sebastiankb commented
from today's TD call, decided to merge

2022-05-04 15:48 UTC, merged