Sync keyword to actions
w3c/wot-thing-description pull request #1491
Opened 2022-05-04 10:15 UTC by egekorkan

fixes #890 

For some reason, I cannot get the keyword to show up in the action affordance table but its description shows up. Also, the SVG is rendered wrong

2022-05-04 12:05 UTC, thjaeckle commented
`sync` is missing from the [Vocabulary term](https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1491/a1c662e...223876d.html#dfn-vocab-term) column in the table.

Great addition, that's also what Eclipse Ditto needs 👍

2022-05-04 12:36 UTC, egekorkan commented
Thanks @thjaeckle . Do you mean that we should add a new terminology term?

Also, these type of actions are implemented in the HTTP Baseline profile as well and I forgot to mention it

2022-05-04 12:42 UTC, thjaeckle commented
What I meant is that the column where the `sync` term should be is empty in the preview:
![image](https://user-images.githubusercontent.com/1331526/166683181-af225f2a-2d93-43fb-bc44-25f9a28f1d49.png)

2022-05-04 13:07 UTC, egekorkan commented
Ah yes, that is why I marked it as a draft. @sebastiankb could you help me with finding out how to introduce the `sync` keyword on the action affordance table?

2022-05-04 13:11 UTC, JKRhb commented
Could it be that the keyword needs to also be included in `td-context.ttl`?

2022-05-04 13:16 UTC, egekorkan commented
> Could it be that the keyword needs to also be included in `td-context.ttl`?

If I do that, npm run render deletes my changes so I am guessing that this file is auto generated?

2022-05-04 13:20 UTC, JKRhb commented
> > Could it be that the keyword needs to also be included in `td-context.ttl`?
> 
> If I do that, npm run render deletes my changes so I am guessing that this file is auto generated?

Oh, sorry, you are right! I think it might actually be `td-context-1.1.jsonld`..?

2022-05-04 13:42 UTC, sebastiankb commented
you need just to update the td-context.jsonld. I added this in the PR and should work now.

2022-05-04 13:44 UTC, thjaeckle commented on context/td-context.jsonld
> +    "isSync" : {
That's what I also would assume looking at the other terms `idempotent`, `safe` for actions ..

2022-05-04 13:44 UTC, danielpeintner reviewed
Question/Comment about naming.
Why do we use `isSync` while we do not use `isSafe` or `isIdempotent`?
I would argue to be consistent.

EDIT: I saw others mentioned this as well...

2022-05-04 13:49 UTC, sebastiankb commented
short hint: if you change a semantic based definition, you typically need to touch 3 files:
- td-context.jsonld
- td-valildation.ttl
- td.ttl / hctl.ttl / wotsec.ttl / jsonschema.ttl

2022-05-04 13:50 UTC, JKRhb commented on context/td-context.jsonld
> +    "isSync" : {
@sebastiankb Hmm, looking at the new diff, I think the sync and isSync need to be swapped?

2022-05-04 13:52 UTC, sebastiankb approved these changes

2022-05-04 16:19 UTC, JKRhb approved these changes

2022-05-05 06:44 UTC, danielpeintner approved these changes

2022-05-18 08:26 UTC, sebastiankb commented
@egekorkan can you check the conflicts

2022-05-18 13:59 UTC, mlagally requested changes
This PR contains changes to normative language that seem to be unrelated.

2022-05-18 15:30 UTC, sebastiankb commented
from today's TD call:
- there was a discussion about the "sync" naming and why not "synchronous" (most preferred one in the group) or "blocking" or "async"
- @egekorkan will provide an update

2022-05-18 15:50 UTC, egekorkan commented
@danielpeintner I have changed to synchronous and also fixed merge conflicts

2022-05-18 16:01 UTC, merged