avoid double encoding for tm:re
w3c/wot-thing-description pull request #1500
Opened 2022-05-09 14:32 UTC by sebastiankb

solves #1410

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1500.html" title="Last updated on May 18, 2022, 3:57 PM UTC (75fd278)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/1500/78cfc50...75fd278.html" title="Last updated on May 18, 2022, 3:57 PM UTC (75fd278)">Diff</a>

2022-05-09 14:55 UTC, aphillips commented
I see how you got here, but I'm not sure that the addition of the note will be that clear. Note that double-encoding would encode the percent sign (the string wouldn't include any non-ASCII characters--the escaping would process ASCII characters reserved in URL). Perhaps instead:

> Portions of the `tm:ref` value might contain non-ASCII characters that require URL ("percent") encoding before use. Before applying escapes to a `tm:ref` value, implementations should check that the value is not already encoded.

2022-05-09 19:41 UTC, sebastiankb commented
@aphillips thanks for your feedback. Text is updated based on you proposal.

2022-05-10 18:42 UTC, egekorkan requested changes

2022-05-10 18:42 UTC, egekorkan commented on index.template.html
> +        encoding before use. Before applying escapes to a <code>tm:ref</code> value, implementations should check that the value is not already
I think we need an RFC assertion here while making sure that the assertion is understandable on its own (implies changes to the sentence)

2022-05-18 15:57 UTC, sebastiankb commented
from today's TD call, decided to merge

2022-05-18 15:59 UTC, sebastiankb commented
from today's TD call, decided to merge.

@egekorkan also agree to keep it as a note

2022-05-18 15:59 UTC, merged