fix tm:required examples
w3c/wot-thing-description pull request #1571
Opened 2022-07-08 12:45 UTC by egekorkan

fixes #1563

2022-07-11 13:42 UTC, danielpeintner requested changes
I think there are some more left

https://github.com/w3c/wot-thing-description/blob/3ccbb14aa818bcfae7e53949786b26102b2a61eb/index.html#L6028-L6031

2022-07-12 13:27 UTC, egekorkan commented
@danielpeintner I have provided fixes for your comment

2022-07-12 13:36 UTC, danielpeintner approved these changes

2022-07-13 13:21 UTC, JKRhb commented
> I mean, even the RFC is giving some warnings that it is not necessarily the case. I think that we cannot just say JSON Pointer since it can have multiple representations.

That is a good point. Would this imply that we should not define a fragment identifier for `application/td+json` due to incompatibilities (resolving #1064)? Or is this question independent of this issue?

Another aspect: Removing the `#` for JSON pointers would imply that the relative `tm:ref` introduced in #1552 need to be changed as well, right? This would probably require changes to the respective assertion (in a follow-up PR).

2022-07-13 14:33 UTC, merged