TD resources next to the spec
w3c/wot-thing-description pull request #1867
Opened 2023-08-08 15:12 UTC by egekorkan

This documents the additional resources next to the TD spec that we maintain. Next commits will detail the usage of those documents.

2023-08-08 22:19 UTC, egekorkan commented
@mahdanoura and @relu91 could you have a look and possibly extend the uses of ontologies and context files?

2023-08-09 10:27 UTC, relu91 approved these changes
I had a look at the changes and I think that overall it is a good description of the current resources managed by us. One thing that we can mention is that in the past we use to have also these alignment ontologies: [schema](https://github.com/w3c/wot-thing-description/blob/main/ontology/td-sdo.ttl) and [sosa](https://github.com/w3c/wot-thing-description/blob/main/ontology/td-sosa.ttl). But I am not even sure if they are up to date with the current status.

2023-08-09 10:34 UTC, relu91 requested changes
On second thought I think we can add these two lines.

2023-08-09 10:34 UTC, relu91 commented on README.md
> +The working document can be found at [context/td-context-1.1.jsonld](./context/td-context-1.1.jsonld) and the version-specific context file can be retrieved from the `@context` value of a TD 1.0 or T
I think we can and a simple sentence to explain the context file is actually a merge of the other files contained in the folder. 
```suggestion
The working document can be found at [context/td-context-1.1.jsonld](./context/td-context-1.1.jsonld) and the version-specific context file can be retrieved from the `@context` value of a TD 1.0 or TD 1.1 instance. **Note** that  [context/td-context-1.1.jsonld](./context/td-context-1.1.jsonld) is the result of the rending process and it should not be edited manually. In practice, the rending process merges [context/td-context.jsonld](./context/td-context.jsonld), [context/json-schema-context.jsonld](./context/json-schema-context.jsonld), [context/wot-security-context.jsonld](./context/wot-security-context.jsonld), [context/hypermedia-context.jsonld](./context/hypermedia-context.jsonld).  
```

2023-08-23 10:07 UTC, egekorkan commented
@relu91 I have applied your suggestion but I had to fix the typo of `rending` to `rendering`

2023-08-23 10:40 UTC, relu91 approved these changes

2023-09-06 14:39 UTC, merged