Fix schema links to static ones
w3c/wot-thing-description pull request #1870
Opened 2023-08-08 22:42 UTC by egekorkan

We should fix these notes. My proposal is to merge this and https://github.com/w3c/wot-thing-description/pull/1861 together and decide on where to serve the content from. It doesn't matter if the schemas come from a new repo, a GitHub release or the publication folder but these links should appear in the REC.

2023-08-09 10:40 UTC, relu91 requested changes
Don't we to update the `$id` [here](https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json#L6) too? 

**Update**: ah probably is it something that we have to change when we decide on the mechanism in #1861

2023-08-09 13:27 UTC, sebastiankb approved these changes

2023-08-23 09:15 UTC, egekorkan commented
> Don't we to update the `$id` [here](https://github.com/w3c/wot-thing-description/blob/main/validation/td-json-schema-validation.json#L6) too?
> 
> **Update**: ah probably is it something that we have to change when we decide on the mechanism in #1861

So I would try to keep the PRs focused for now. This one changes the index.html and once we agree on the link, we can change the resource behind it easily (where the `$id` will be present)

2023-08-30 20:24 UTC, egekorkan commented
Merging as communicated at https://lists.w3.org/Archives/Member/member-wot-wg/2023Aug/0003.html

2023-08-30 20:24 UTC, merged