toolchain description update
w3c/wot-thing-description pull request #1933
Opened 2023-12-04 12:40 UTC by mahdanoura

addresses the second point in #1920

2023-12-11 23:00 UTC, egekorkan requested changes

2023-12-11 23:00 UTC, egekorkan commented on toolchain/README.md
> +The Parser Creation process is mainly performed by a developer using a 2-step process. The grammar is developed manually using to context-free grammar according to the semantics of STTL language. The
```suggestion
The Parser Creation process is mainly performed by a developer using a 2-step process. The grammar is developed manually using a context-free grammar according to the semantics of STTL language. Then, the [Jison](https://gerhobbelt.github.io/jison/docs/) tool takes the grammar as input and outputs a JavaScript file capable of parsing the language described by that grammar. The generated script is then used to parse visualization template inputs in the STTL Engine.
```

2023-12-13 16:34 UTC, egekorkan commented
Another point from today's call:
- We should change the diagram's semantic web expert to "TD Task Force Participants" and write that in the readme that it is the main manual step.

2024-01-17 10:00 UTC, mahdanoura commented on toolchain/README.md
>  2. ***WoT Toolchain***
```suggestion
2. ***Render Script***
```

2024-01-17 10:00 UTC, mahdanoura commented on toolchain/README.md
> +The WoT Toolchain is a shell script (render.sh), which manages the interaction between different Node.js scripts developed to achieve different objectives. It receives the different JSON-LD context f
```suggestion
The Render Script[https://github.com/w3c/wot-thing-description/blob/main/render.sh](url) is a shell script which manages the interaction between different Node.js scripts developed to achieve different objectives. First, it receives the different JSON-LD context files for each ontology in the TD model developed in the previous steps and aggregates them into one, resulting in [td-context-1.1.jsonld](https://github.com/w3c/wot-thing-description/blob/main/context/td-context-1.1.jsonld). The JSON-LD context file is then converted into RDF Turtle representation format ([td-context.ttl](https://github.com/w3c/wot-thing-description/blob/main/context/td-context.ttl)).
```

2024-01-17 10:00 UTC, mahdanoura commented on toolchain/README.md
> +The STTL engine takes different RDF graphs: TD model ontologies, SHACL shapes (validation/td-validation.ttl), merged context (context/td-context.ttl), a transformation (a set of templates), and a spe
```suggestion
The STTL engine takes different artifacts produced in the previous steps as input, including TD model ontologies, [SHACL shapes](https://github.com/w3c/wot-thing-description/blob/main/validation/td-validation.ttl), [merged context](https://github.com/w3c/wot-thing-description/blob/main/context/td-context-1.1.jsonld), a set of STTL transformation templates, and a specific starting node. The starting node is the HTML node pointing to the WoT Things Description file. The TD model ontologies and SHACL shapes are loaded and stored in an RDF store for semantic processing and querying. Then, the STTL templates are parsed according to the parser developed by the Parser Creation actor. This is followed by matching the input HTML node with one of the transformation names specified in the template. A template in a transformation may apply other templates or include different utility functions or SPARQL functions. Therefore, the Apply Template sub-process identifies these different cases and applies the rules which includes the following activities: evaluate patterns, variables and expressions in a template, construct the query to execute using a JSON format, and executing the query on the RDF graph. The output is generated HTML textual output format corresponding to the index.html file of the TD specification and the different ontology specifications.
```

2024-01-17 10:00 UTC, mahdanoura commented on toolchain/README.md
> +The STTL engine takes different RDF graphs: TD model ontologies, SHACL shapes (validation/td-validation.ttl), merged context (context/td-context.ttl), a transformation (a set of templates), and a spe
Will create a PR for this for a second iteration

2024-01-17 13:18 UTC, egekorkan requested changes
minor formatting issues

2024-01-17 13:18 UTC, egekorkan commented on toolchain/README.md
> +The Semantic Web Expert has the main responsibility to iteratively define the schema of different TD model specifications such as TD core, TM, WoTsec, HCTL or any extensions required. Also, the JSON
```suggestion
The Semantic Web Expert has the main responsibility to iteratively define the schema of different TD model specifications such as TD core, TM, WoTsec, HCTL or any extensions required. Also, the JSON Schema definition is defined for syntactical validation of JSON-LD data and Shapes Constraint Language (SHACL) shapes for validating RDF graphs. These different tasks are performed in an adhoc manner until agreement is achieved among the experts. In addition, the experts define a set of transformations for the specification generation according to the SPARQL Template Transformation Language (STTL). The templates expressed in STTL describe different rules for transforming a source RDF graph into a result text.
```

2024-01-17 14:31 UTC, egekorkan approved these changes

2024-01-17 15:40 UTC, mjkoster commented
Meeting 1/17/2024
- Merge now and refine:
- Add a high level diagram
- Add detail diagrams as needed
- Add explanatory text as needed

2024-01-17 15:40 UTC, merged